In [2]:
import nltk
import string
import re
import math
import numpy as np
from collections import defaultdict
from sklearn.metrics import f1_score, accuracy_score, confusion_matrix, ConfusionMatrixDisplay
import matplotlib.pyplot as plt
from sklearn.model_selection import train_test_split
import random
from sklearn.feature_extraction.text import CountVectorizer
from sklearn.neighbors import KNeighborsClassifier
from sklearn.tree import DecisionTreeClassifier
from sklearn.svm import SVC
from sklearn.metrics import classification_report, ConfusionMatrixDisplay



In [3]:
# (aplicar UKB o Lesk)
import nltk
nltk.download('movie_reviews')
from nltk.corpus import movie_reviews as mr

[nltk_data] Downloading package movie_reviews to
[nltk_data]     C:\Users\11ser\AppData\Roaming\nltk_data...
[nltk_data]   Unzipping corpora\movie_reviews.zip.


In [4]:
#avaluacio correcta separacio entre corpus de train i validacio, optimitzacio hiperparàmetres, study i anàlisis (com afecta afegir més o menys paraules), 

In [5]:
print(len(mr.fileids('pos')))
print(len(mr.fileids('neg')))

1000
1000


In [6]:
def preprocessar(text):  
    # Convert text to lowercase
    text = [word.lower() for word in text]
    # no del tot segur si eliminar stopwords o no
    #stopwords = set(['a', 'an', 'the', 'and', 'but', 'or', 'for', 'nor', 'on', 'at', 'to', 'by', 'in', 'of', 'with', 'is', 'are', 'am', 'was', 'were'])
    cleaned_text = []
    altres = set([' ', '-','t','/','s','_'])
    for word in text:
        # Remove punctuation
        # Remove punctuation in a more comprehensive way
        
        word =re.sub(r'\s[^\w\s]\s', ' ', word)
        # Remove all kinds of punctuation including parentheses
        word = re.sub(r'[\(\)\[\]\{\}\.,;:!?\"\'`_]', '', word)
        word = re.sub(r'\d+', ' ', word) # remove numbers
    
        
        # Remove apostrophes and everything after them
        
        
        # Skip empty strings and stopwords
        if word and word not in altres: #and word not in stopwords and len(word)>1: 
            cleaned_text.append(word)

    return cleaned_text

In [9]:
display(mr.fileids('pos')[:10])

['pos/cv000_29590.txt',
 'pos/cv001_18431.txt',
 'pos/cv002_15918.txt',
 'pos/cv003_11664.txt',
 'pos/cv004_11636.txt',
 'pos/cv005_29443.txt',
 'pos/cv006_15448.txt',
 'pos/cv007_4968.txt',
 'pos/cv008_29435.txt',
 'pos/cv009_29592.txt']

In [10]:
print(mr.words(mr.fileids()[0]))

['plot', ':', 'two', 'teen', 'couples', 'go', 'to', ...]


In [11]:
llista_X = [preprocessar(mr.words(i)) for i in mr.fileids()]
llista_Y = []
for i in mr.fileids():
    if 'pos' in i:
        llista_Y.append('pos')
    else:
        llista_Y.append('neg')


In [14]:
# Convert each list of words in llista_X into a string
llista_X_strings = [' '.join(words) for words in llista_X]

display(llista_X_strings[2:100][:10])

['it is movies like these that make a jaded movie viewer thankful for the invention of the timex indiglo watch based on the late television show by the same name the mod squad tells the tale of three reformed criminals under the employ of the police to go undercover however things go wrong as evidence gets stolen and they are immediately under suspicion of course the ads make it seem like so much more quick cuts cool music claire dane nice hair and cute outfits car chases stuff blowing up and the like sounds like a cool movie does it not after the first fifteen minutes it quickly becomes apparent that it is not the mod squad is certainly a slick looking production complete with nice hair and costumes but that simply isn enough the film is best described as a cross between an hour long cop show and a music video both stretched out into the span of an hour and a half and with it comes every single clich it doesn really matter that the film is based on a television show as most of the plo

In [15]:
vectorizer = CountVectorizer()
X = vectorizer.fit_transform(llista_X_strings)

In [16]:
vectorizer.get_feature_names_out()

array(['aa', 'aaa', 'aaaaaaaaah', ..., 'zwigoff', 'zycie', 'zzzzzzz'],
      dtype=object)

In [17]:
print(X.toarray())


[[0 0 0 ... 0 0 0]
 [0 0 0 ... 0 0 0]
 [0 0 0 ... 0 0 0]
 ...
 [0 0 0 ... 0 0 0]
 [0 0 0 ... 0 0 0]
 [0 0 0 ... 0 0 0]]


In [18]:
X_train,X_test,Y_train,Y_test = train_test_split(X,llista_Y, train_size = 0.8, test_size = 0.2)

In [19]:
knn = KNeighborsClassifier(n_neighbors=10, 
                                p=1, 
                                metric='minkowski')
knn.fit(X_train, Y_train)


Y_test_pred = knn.predict(X_test)

        
accuracy = accuracy_score(Y_test, Y_test_pred)

print(f"Validation Accuracy: {accuracy}")
#y_val_pred = knn.predict(X_v)

        
#accuracy = accuracy_score(y_val, y_val_pred)


Validation Accuracy: 0.5475


In [20]:
tree_model = DecisionTreeClassifier(criterion = 'gini', max_depth=12, min_samples_split = 12, random_state=1)


tree_model.fit(X_train, Y_train)

    
Y_test_pred = tree_model.predict(X_test)


accuracy = accuracy_score(Y_test, Y_test_pred)

print(f"Validation Accuracy: {accuracy}")

Validation Accuracy: 0.68


In [21]:
svm = SVC(kernel='rbf', C=10, random_state=1, probability=True)


svm.fit(X_train, Y_train)

       
Y_test_pred = svm.predict(X_test)

  
accuracy = accuracy_score(Y_test, Y_test_pred)

print(f"Validation Accuracy: {accuracy}")

Validation Accuracy: 0.8275
